macro(tuc_discover_tests target)
get_target_property(sources ${target} SOURCES)
foreach(source  ${sources})
	file(STRINGS ${CMAKE_CURRENT_SOURCE_DIR}/${source} tests REGEX "TEST\\(.*\\)")
	foreach(test_parsed ${tests})
		string(REGEX MATCH "\\\(([^)]+)\\\)" test ${test_parsed})
		message(DEBUG "Add test with test=${CMAKE_MATCH_1}")
		add_test(NAME ${CMAKE_MATCH_1} COMMAND ${target} --tuc-filter=${CMAKE_MATCH_1})
	endforeach()
endforeach()
endmacro()
